// Delerium engine — album-era (Faces -> Semantic Spaces -> Karma -> Poem).
// NOT the trance-remix identity. Domains: 'E' electronic, 'A' acoustic, 'B' both.
//
// Rewrite (2026-07-09): fix "tempo was the only real change". Two changes:
//   1) Pools DEEPENED to album-scale and DE-OVERLAPPED so each character owns a
//      distinct pad / vocal / movement signature (Sacred/Ethereal/Firefly no longer
//      share cathedral-pad + vocoder + delay-throws).
//   2) Interplay restructured as attach-clauses (tails that hang off already-named
//      instruments) so the resolver can WEAVE it into the style string per the
//      approved gold-standard format — never re-naming an instrument.

const P = {
  pads: {
    cathedralPad:  { t: 'slowly swelling cathedral-reverb analog pad', d: 'E' },
    darkDrone:     { t: 'dark evolving drone bed', d: 'E' },
    glassyPad:     { t: 'glassy digital pad with shimmering high partials', d: 'E' },
    stringWash:    { t: 'warm string-synth wash', d: 'E' },
    metallicDrone: { t: 'bowed metallic drone', d: 'B' },
    reversedPad:   { t: 'reversed pad swell into the downbeat', d: 'E' },
    harmoniumDrone:{ t: 'sustained harmonium drone', d: 'A' },
    celloDroneBed: { t: 'bowed cello drone bed', d: 'A' },
    choirPad:      { t: 'sustained wordless choir pad', d: 'E' },
    analogueSwell: { t: 'warm analogue polysynth swell', d: 'E' },
    glacialPad:    { t: 'glacial slow-attack ambient pad', d: 'E' },
    tanpuraBed:    { t: 'shimmering tanpura drone bed', d: 'A' },
    feltMalletBed: { t: 'soft felt-mallet resonant bed', d: 'A' },
    jarrePad:      { t: 'spacey analog Jarre-style lead pad', d: 'E' },
    broodingPad:   { t: 'brooding dark atmospheric synth pad', d: 'E' },
    mellotronBed:  { t: 'Mellotron choir-and-flute pad', d: 'B' },
    fmCrystalPad:  { t: 'glassy FM crystalline pad', d: 'E' },
    warmStringEns: { t: 'warm sampled-string ensemble pad', d: 'B' },
    airVocalPad:   { t: 'airy layered vocal-synth pad', d: 'E' },
  },
  bass: {
    subBass:    { t: 'deep sustained sub-bass', d: 'E' },
    seqBass:    { t: 'sequenced synth bass pulsing eighth notes', d: 'E' },
    analogBass: { t: 'slow legato round analog bass', d: 'E' },
    fretless:   { t: 'fretless bass glide', d: 'B' },
    upright:    { t: 'slow plucked upright acoustic bass', d: 'A' },
    oudLow:     { t: 'low oud register', d: 'A' },
    pulsingBass:{ t: 'pulsing filtered synth bass', d: 'E' },
    warmSine:   { t: 'warm sine sub with a soft attack', d: 'E' },
    seqDriveBass:{ t: 'rolling sequenced bassline driving the groove', d: 'E' },
    filterBass: { t: 'warm filtered analog bassline', d: 'E' },
    dubBass:    { t: 'deep dub bassline with a long decay', d: 'E' },
  },
  lead: {
    duduk:     { t: 'sustained duduk lead', d: 'A' },
    bambooFl:  { t: 'bamboo flute motif', d: 'A' },
    piano:     { t: 'sparse grand-piano figure', d: 'A' },
    synthArp:  { t: 'plucked synth arpeggio lead', d: 'E' },
    sitar:     { t: 'sitar melodic phrase', d: 'A' },
    celloLead: { t: 'long-phrased bowed cello lead', d: 'A' },
    fmBell:    { t: 'glassy FM bell lead', d: 'E' },
    detunedLd: { t: 'detuned analog synth lead with slow portamento', d: 'E' },
    panFlute:  { t: 'breathy pan-flute melody', d: 'A' },
    ney:       { t: 'reedy ney flute lead', d: 'A' },
    erhu:      { t: 'bowed erhu melodic line', d: 'A' },
    ebowGuitar:{ t: 'ebow sustained guitar lead', d: 'B' },
    glassPluck:{ t: 'glassy plucked digital lead', d: 'E' },
    harpFigure:{ t: 'a plucked harp figure', d: 'A' },
    nylonGtr:  { t: 'a nylon acoustic-guitar motif', d: 'A' },
    shakuhachi:{ t: 'a breathy shakuhachi flute lead', d: 'A' },
    bansuri:   { t: 'a bansuri bamboo-flute melody', d: 'A' },
  },
  harmony: {
    minorModal:{ t: 'slow minor-modal chord changes', d: 'B' },
    suspended: { t: 'suspended chords resolving on the chorus lift', d: 'B' },
    droneTonic:{ t: 'an unresolved static drone-tonic', d: 'B' },
    add9:      { t: 'lush add9 chord voicings', d: 'B' },
    phrygian:  { t: 'a dark phrygian cadence', d: 'B' },
    majorLift: { t: 'a major-key chord lift on the chorus', d: 'B' },
    plagalCadence:{ t: 'a plagal cadence resolving to the tonic', d: 'B' },
    modalResolve: { t: 'a modal cadence landing on the root', d: 'B' },
    minorToMajor: { t: 'a minor-to-relative-major resolution on the chorus', d: 'B' },
    risingProg:   { t: 'a rising chord progression that resolves upward', d: 'B' },
    sacredCadence:{ t: 'a sacred choral cadence resolving on the final chord', d: 'B' },
  },
  voice: {
    latinChant:   { t: 'distant monastic Latin chant', d: 'A' },
    femaleWash:   { t: 'an ethereal wordless female vocal wash', d: 'A' },
    euroChoir:    { t: 'an Eastern-European choir texture', d: 'A' },
    throatChant:  { t: 'a throat-overtone chant drone', d: 'A' },
    vocalChops:   { t: 'rhythmic sampled ethnic vocal chops', d: 'B' },
    vocoderPad:   { t: 'a vocoded wordless vocal pad', d: 'E' },
    granularVox:  { t: 'a granular stretched-vocal drone', d: 'E' },
    sanskritChant:{ t: 'distant Sanskrit vocal chant', d: 'A' },
    breathyFemale:{ t: 'a breathy close female vocal texture', d: 'A' },
    maleDrone:    { t: 'a low male vocal drone', d: 'A' },
    childChoir:   { t: "a distant children's choir wash", d: 'A' },
    gregorianMale:{ t: 'Gregorian-style male chant', d: 'A' },
    liveChoirSwell:{ t: 'a live choir swell', d: 'A' },
    femaleHarmony: { t: 'layered ethereal female vocal harmonies', d: 'A' },
    bakaChant:     { t: 'a Baka-forest-style pygmy chant', d: 'A' },
    prayerCall:    { t: 'a distant call-to-prayer melisma', d: 'A' },
  },
  color: {
    fingerCymb: { t: 'finger cymbals and bells', d: 'A' },
    dulcimer:   { t: 'a hammered dulcimer run', d: 'A' },
    sarangi:    { t: 'a bowed sarangi ornament', d: 'A' },
    gong:       { t: 'a gong swell', d: 'A' },
    kalimba:    { t: 'a kalimba figure', d: 'A' },
    bellArp:    { t: 'a bell-synth arpeggio sparkle', d: 'E' },
    revStab:    { t: 'a reversed synth-stab accent', d: 'E' },
    windChimes: { t: 'a wind-chime shimmer', d: 'A' },
    santoor:    { t: 'a santoor tremolo run', d: 'A' },
    prepPiano:  { t: 'a prepared-piano pluck', d: 'A' },
    glocken:    { t: 'a glockenspiel sparkle', d: 'B' },
    harpGliss:  { t: 'a harp glissando', d: 'A' },
    handDrumFill:{ t: 'a tuned hand-drum fill', d: 'A' },
    tambShaker: { t: 'tambourine and shaker accents', d: 'A' },
    tablaFill:  { t: 'a tabla fill', d: 'A' },
  },
  movement: {
    filterLFO:   { t: 'a slow filter LFO sweep', d: 'E' },
    delayThrows: { t: 'tempo-synced delay throws', d: 'E' },
    autopan:     { t: 'a wide stereo autopan', d: 'E' },
    reversedTr:  { t: 'reversed-swell transitions', d: 'E' },
    reverbTail:  { t: 'a long cathedral reverb tail', d: 'E' },
    tremoloSwell:{ t: 'tremolo bowed-string swells', d: 'A' },
    handCresc:   { t: 'rolling hand-percussion crescendos', d: 'A' },
    dubEcho:     { t: 'dub delay echoes as a second voice', d: 'E' },
    risers:      { t: 'filtered-noise risers into the lift', d: 'E' },
    panSweep:    { t: 'a slow stereo pan sweep', d: 'E' },
    phaserSweep: { t: 'a slow phaser sweep across the pads', d: 'E' },
    flangeVocal: { t: 'a flanged sweep on the vocal', d: 'E' },
    tapeEcho:    { t: 'analog tape-echo repeats', d: 'E' },
    filterGate:  { t: 'a rhythmic filter-gate pulse', d: 'E' },
  },
};

const DRUMS = {
  worldbeat: ['deep frame drum','a tabla pattern','a dumbek groove','a hand-played djembe','congas and shakers with tambourine'],
  softDown:  ['a subdued soft programmed kick','a brushed programmed snare','a trip-hop-leaning downtempo groove','a soft measured downtempo beat'],
  firefly:   ['a denser driving programmed pulse','a propulsive sequenced groove'],
  hybrid:    ['a programmed kick under live hand percussion','a downtempo beat laced with hand percussion'],
};

const r = (role, ...keys) => keys.map(k => P[role][k]);

const CHARACTERS = {
  gothicAmbient: {
    label: 'Gothic Ambient', source: 'Faces / Morpheus',
    genre: 'Delerium Style, dark ritual ambient',
    beatless: true, energy: 'low', colorChance: 0.5,
    drums: { primary: null, secondary: null },
    pools: {
      pads:     r('pads','darkDrone','metallicDrone','glacialPad','celloDroneBed','broodingPad','mellotronBed'),
      bass:     r('bass','subBass','fretless','warmSine','dubBass','filterBass'),
      harmony:  r('harmony','droneTonic','phrygian','modalResolve','sacredCadence'),
      voice:    r('voice','throatChant','granularVox','maleDrone','bakaChant','prayerCall'),
      lead:     r('lead','celloLead','ebowGuitar','ney','shakuhachi'),
      color:    r('color','gong','windChimes','prepPiano','harpGliss'),
      movement: r('movement','reversedTr','reverbTail','tremoloSwell','phaserSweep','tapeEcho'),
    },
  },
  worldbeatRitual: {
    label: 'Worldbeat Ritual', source: 'Semantic Spaces',
    genre: 'Delerium Style, worldbeat downtempo, tribal ethereal',
    beatless: false, bpm: [84,96], energy: 'low to medium', colorChance: 0.55,
    drums: { primary: 'worldbeat', secondary: null },
    pools: {
      pads:     r('pads','harmoniumDrone','tanpuraBed','darkDrone','mellotronBed','broodingPad'),
      bass:     r('bass','subBass','oudLow','upright','dubBass','filterBass'),
      harmony:  r('harmony','droneTonic','minorModal','phrygian','modalResolve','sacredCadence'),
      voice:    r('voice','euroChoir','sanskritChant','throatChant','vocalChops','bakaChant','liveChoirSwell','prayerCall'),
      lead:     r('lead','duduk','bambooFl','sitar','ney','erhu','bansuri','shakuhachi','harpFigure'),
      color:    r('color','fingerCymb','dulcimer','sarangi','santoor','tablaFill','handDrumFill','tambShaker','harpGliss'),
      movement: r('movement','filterLFO','handCresc','dubEcho','tapeEcho','filterGate'),
    },
  },
  sacredDowntempo: {
    label: 'Sacred Downtempo', source: 'Silence / Karma',
    genre: 'Delerium Style, sacred ethereal downtempo',
    beatless: false, bpm: [92,100], energy: 'medium', colorChance: 0.45,
    drums: { primary: 'softDown', secondary: 'hybrid' },
    pools: {
      pads:     r('pads','cathedralPad','harmoniumDrone','choirPad','feltMalletBed','warmStringEns','mellotronBed'),
      bass:     r('bass','subBass','upright','warmSine','filterBass','dubBass'),
      harmony:  r('harmony','minorModal','suspended','add9','sacredCadence','plagalCadence','minorToMajor'),
      voice:    r('voice','latinChant','gregorianMale','childChoir','femaleWash','liveChoirSwell','femaleHarmony','prayerCall'),
      lead:     r('lead','piano','duduk','celloLead','panFlute','harpFigure','nylonGtr','shakuhachi'),
      color:    r('color','fingerCymb','glocken','prepPiano','harpGliss','handDrumFill','tambShaker'),
      movement: r('movement','delayThrows','reversedTr','reverbTail','phaserSweep','tapeEcho'),
    },
  },
  ethereal: {
    label: 'Ethereal', source: 'Innocente / Poem',
    genre: 'Delerium Style, ethereal downtempo electronica',
    beatless: false, bpm: [100,112], energy: 'medium', colorChance: 0.4,
    drums: { primary: 'softDown', secondary: 'hybrid' },
    pools: {
      pads:     r('pads','cathedralPad','glassyPad','stringWash','analogueSwell','jarrePad','fmCrystalPad','airVocalPad'),
      bass:     r('bass','analogBass','upright','warmSine','fretless','seqDriveBass','filterBass'),
      harmony:  r('harmony','suspended','add9','majorLift','minorToMajor','risingProg','plagalCadence'),
      voice:    r('voice','femaleWash','breathyFemale','vocoderPad','granularVox','femaleHarmony','liveChoirSwell'),
      lead:     r('lead','piano','synthArp','detunedLd','glassPluck','ebowGuitar','nylonGtr','harpFigure','shakuhachi'),
      color:    r('color','kalimba','bellArp','glocken','harpGliss','tambShaker'),
      movement: r('movement','delayThrows','autopan','dubEcho','panSweep','phaserSweep','flangeVocal','tapeEcho'),
    },
  },
  firefly: {
    label: 'Firefly', source: 'Euphoria',
    genre: 'Delerium Style, driving ethereal downtempo',
    beatless: false, bpm: [112,126], energy: 'medium to high', colorChance: 0.4,
    drums: { primary: 'firefly', secondary: 'hybrid' },
    pools: {
      pads:     r('pads','glassyPad','reversedPad','analogueSwell','choirPad','fmCrystalPad','airVocalPad','jarrePad'),
      bass:     r('bass','seqBass','pulsingBass','subBass','seqDriveBass','filterBass','dubBass'),
      harmony:  r('harmony','suspended','majorLift','minorModal','risingProg','minorToMajor'),
      voice:    r('voice','vocoderPad','breathyFemale','vocalChops','femaleWash','femaleHarmony','liveChoirSwell'),
      lead:     r('lead','synthArp','fmBell','detunedLd','glassPluck'),
      color:    r('color','bellArp','revStab','glocken','harpGliss'),
      movement: r('movement','delayThrows','autopan','risers','panSweep','flangeVocal','tapeEcho','filterGate'),
    },
  },
};

const INTERPLAY = {
  gothicAmbient: {
    conversation: ['surfacing alone against deep space then dissolving back into the texture',
                   'emerging and receding without hierarchy each equal in the field',
                   'cross-fading so the melody dissolves into atmosphere'],
    foundation:   ['holding a single harmonic centre with everything suspended above',
                   'anchoring in slow motion while the timbres drift unmoving'],
    arc:          ['evolving so slowly that change is felt rather than heard',
                   'replacing motion with the slow turn of timbre',
                   'sustaining tension through what never resolves',
                   'finally settling onto a single resolved chord',
                   'resolving at last into a sustained tonic'],
    voiceRel:     ['drifting over the top without hierarchy','breathing at the edge of the field','hanging in the deep reverb'],
    colorRel:     ['ringing once into the silence','surfacing briefly then gone'],
  },
  worldbeatRitual: {
    conversation: ['trading phrases over the percussion','stating the melody while the wash breathes beneath',
                   'answered now and then by an ornament rising through the mix'],
    foundation:   ['locked with the hand drums in a rolling ritual pocket',
                   'interlocking in a loose earthy groove','anchoring while the hand drums drive above'],
    arc:          ['building the ritual organically as voices layer in one at a time',
                   'swelling and receding in long ceremonial waves','rising through added hand drums then opening back to space',
                   'resolving the ritual onto a final grounded chord'],
    voiceRel:     ['breathing beneath the lead','chanting in the distance','layering in call-and-response with the flute'],
    colorRel:     ['ornamenting the gaps between phrases','sparkling through the ritual','answering the drums'],
  },
  sacredDowntempo: {
    conversation: ['rising together then answered by soft chord swells','hanging over the chant with space between statements',
                   'trading the foreground unhurried'],
    foundation:   ['locked in a slow reverent pocket','sustaining long tones beneath the pads anchoring without intruding',
                   'holding steady while the low end floats'],
    arc:          ['stacking toward a lush sacred peak then receding','opening gradually with each voice given room to breathe',
                   'built through rising harmony then released into open sustained chords',
                   'resolving into a lush final cadence'],
    voiceRel:     ['answering the lead from the reverb','rising over the chant','trading the foreground with the melody'],
    colorRel:     ['marking the phrase ends','threading through the sacred space','answering the choir'],
  },
  ethereal: {
    conversation: ['trading phrases in warm ethereal dialogue','floating free over the harmony',
                   'drifting over the chords answered by a second voice'],
    foundation:   ['rolling forward in a smooth unhurried pocket','gliding beneath the pulse tied to the cycle above',
                   'anchoring while the low end moves smooth and unhurried'],
    arc:          ['entering one at a time with air around each voice','swelling toward an emotional lift then settling back',
                   'layering toward immersion then thinning to open space',
                   'resolving into a warm final chord as it closes'],
    voiceRel:     ['answering the lead in warm dialogue','entering with air around it','drifting over the harmony'],
    colorRel:     ['threading through the spaces','shimmering between phrases','tracing the top of the harmony'],
  },
  firefly: {
    conversation: ['interlocking in a tight bright weave','answered by chord stabs over the drive',
                   'trading with their own delayed repeats in call-and-response'],
    foundation:   ['locked tight and propulsive','chugging steady and forward beneath the layers',
                   'anchoring as a relentless low pulse while the synths climb over it'],
    arc:          ['building through added layers toward an open peak','opening over the drive into a full-energy lift',
                   'stacking through rising layers then released into the chorus',
                   'resolving the climb onto a bright final chord'],
    voiceRel:     ['climbing over the drive','answering the lead','riding above the pulse'],
    colorRel:     ['sparkling over the groove','accenting the lift','flickering between the beats'],
  },
};

export const DELERIUM = {
  id: 'Delerium',
  styleAnchor: 'Delerium Style',
  master: P,
  drums: DRUMS,
  characters: CHARACTERS,
  interplay: INTERPLAY,
  sourceNegative: [
    'trance','four-on-the-floor','club anthem','EDM drop','supersaw',
    'hard kick','festival synths','big-room','pop hooks','radio pop',
  ],
  order: ['pads','harmony','bass','drums','voice','lead','color','movement'],
};
